-- CREATE VIEW banking_app.cex_sample_earners AS
-- SELECT
-- 	"QINTRVYR" ::INTEGER AS year,
-- 	"QINTRVMO" ::INTEGER AS month,
-- 	TO_DATE (CONCAT ("QINTRVYR", "QINTRVMO"), 'YYYYMM') AS date,
-- 	CASE
-- 		WHEN "REGION" IS NOT NULL AND "REGION" != '' THEN "REGION" ::INTEGER
-- 		WHEN "REGION" IS NULL OR "REGION" = '' THEN 0
-- 	END AS region,
-- 	CASE
-- 		WHEN "REGION" = '1' THEN 'Northeast'
-- 		WHEN "REGION" = '2' THEN 'Midwest'
-- 		WHEN "REGION" = '3' THEN 'South'
-- 		WHEN "REGION" = '4' THEN 'West'
-- 		WHEN "REGION" IS NULL OR "REGION" = '' THEN 'none'
-- 	END AS region_name,
-- 	COUNT("NEWID") AS total_sample,
--   COUNT("NEWID") FILTER(WHERE "EARNCOMP" = '1') AS ref_only,
--   ROUND(CAST(COUNT("NEWID") FILTER (WHERE "EARNCOMP" = '1') AS NUMERIC)/COUNT("NEWID"), 4) * 100 AS percent_ref_only,
--   SUM("FINCBTAX" ::DECIMAL) FILTER (WHERE "EARNCOMP" = '1') / COUNT("FINCBTAX") FILTER (WHERE "EARNCOMP" = '1') AS avg_family_pretax_income_ref_only,
--   COUNT("NEWID") FILTER(WHERE "EARNCOMP" = '2') AS ref_and_spouse,
--   ROUND(CAST(COUNT("NEWID") FILTER (WHERE "EARNCOMP" = '2') AS NUMERIC)/COUNT("NEWID"), 4) * 100 AS percent_ref_and_spouse,
--   SUM("FINCBTAX" ::DECIMAL) FILTER (WHERE "EARNCOMP" = '2') / COUNT("FINCBTAX") FILTER (WHERE "EARNCOMP" = '2') AS avg_family_pretax_income_ref_and_spouse,
--   COUNT("NEWID") FILTER(WHERE "EARNCOMP" = '3') AS ref_and_spouse_and_others,
--   ROUND(CAST(COUNT("NEWID") FILTER (WHERE "EARNCOMP" = '3') AS NUMERIC)/COUNT("NEWID"), 4) * 100 AS percent_ref_and_spouse_and_others,
--   SUM("FINCBTAX" ::DECIMAL) FILTER (WHERE "EARNCOMP" = '3') / COUNT("FINCBTAX") FILTER (WHERE "EARNCOMP" = '3') AS avg_family_pretax_income_ref_spouse_and_others,
--   COUNT("NEWID") FILTER(WHERE "EARNCOMP" = '4') AS ref_and_others,
--   ROUND(CAST(COUNT("NEWID") FILTER (WHERE "EARNCOMP" = '4') AS NUMERIC)/COUNT("NEWID"), 4) * 100 AS percent_ref_and_others,
--   SUM("FINCBTAX" ::DECIMAL) FILTER (WHERE "EARNCOMP" = '4') / COUNT("FINCBTAX") FILTER (WHERE "EARNCOMP" = '4') AS avg_family_pretax_income_ref_and_others,
--   COUNT("NEWID") FILTER(WHERE "EARNCOMP" = '5') AS spouse_only,
--   ROUND(CAST(COUNT("NEWID") FILTER (WHERE "EARNCOMP" = '5') AS NUMERIC)/COUNT("NEWID"), 4) * 100 AS percent_spouse_only,
--   SUM("FINCBTAX" ::DECIMAL) FILTER (WHERE "EARNCOMP" = '5') / COUNT("FINCBTAX") FILTER (WHERE "EARNCOMP" = '5') AS avg_family_pretax_income_spouse_only,
--   COUNT("NEWID") FILTER(WHERE "EARNCOMP" = '6') AS spouse_and_others,
--   ROUND(CAST(COUNT("NEWID") FILTER (WHERE "EARNCOMP" = '6') AS NUMERIC)/COUNT("NEWID"), 4) * 100 AS percent_spouse_and_others,
--   SUM("FINCBTAX" ::DECIMAL) FILTER (WHERE "EARNCOMP" = '6') / COUNT("FINCBTAX") FILTER (WHERE "EARNCOMP" = '6') AS avg_family_pretax_income_spouse_and_others,
--   COUNT("NEWID") FILTER(WHERE "EARNCOMP" = '7') AS others_only,
--   ROUND(CAST(COUNT("NEWID") FILTER (WHERE "EARNCOMP" = '7') AS NUMERIC)/COUNT("NEWID"), 4) * 100 AS percent_others_only,
--   SUM("FINCBTAX" ::DECIMAL) FILTER (WHERE "EARNCOMP" = '7') / COUNT("FINCBTAX") FILTER (WHERE "EARNCOMP" = '7') AS avg_family_pretax_income_others_only,
--   COUNT("NEWID") FILTER(WHERE "EARNCOMP" = '8') AS no_earners,
--   ROUND(CAST(COUNT("NEWID") FILTER (WHERE "EARNCOMP" = '8') AS NUMERIC)/COUNT("NEWID"), 4) * 100 AS percent_no_earners,
--   SUM("FINCBTAX" ::DECIMAL) FILTER (WHERE "EARNCOMP" = '8') / COUNT("FINCBTAX") FILTER (WHERE "EARNCOMP" = '8') AS avg_family_pretax_income_no_earners
-- FROM data_import.cex_pumd_fmli
-- GROUP BY "QINTRVYR", "QINTRVMO", "REGION"
-- ORDER BY year, date, region

CREATE VIEW banking_app.cex_sample_age AS
SELECT
	"QINTRVYR" ::INTEGER AS year,
	"QINTRVMO" ::INTEGER AS month,
	TO_DATE (CONCAT ("QINTRVYR", "QINTRVMO"), 'YYYYMM') AS date,
	CASE
		WHEN "REGION" IS NOT NULL AND "REGION" != '' THEN "REGION" ::INTEGER
		WHEN "REGION" IS NULL OR "REGION" = '' THEN 0
	END AS region,
	CASE
		WHEN "REGION" = '1' THEN 'Northeast'
		WHEN "REGION" = '2' THEN 'Midwest'
		WHEN "REGION" = '3' THEN 'South'
		WHEN "REGION" = '4' THEN 'West'
		WHEN "REGION" IS NULL OR "REGION" = '' THEN 'none'
	END AS region_name,
	COUNT("NEWID") AS total_sample,
		COUNT("AGE2") AS total_spouse,
		COUNT("NEWID") FILTER (WHERE "AGE_REF" ::DECIMAL <= 18) AS ref_18_under,
    SUM("FINCBTAX" ::DECIMAL) FILTER (WHERE "AGE_REF" ::DECIMAL <= 18) / COUNT("FINCBTAX") FILTER (WHERE "AGE_REF" ::DECIMAL <= 18) AS avg_family_pretax_income_ref_18_under,
		COUNT("AGE2") FILTER (WHERE "AGE2" <> '' AND "AGE2" ::DECIMAL <= 18) AS spouse_18_under,
		COUNT("NEWID") FILTER (WHERE "AGE_REF" ::DECIMAL BETWEEN 19 AND 25) AS ref_19_25,
    SUM("FINCBTAX" ::DECIMAL) FILTER (WHERE "AGE_REF" ::DECIMAL BETWEEN 19 AND 25) / COUNT("FINCBTAX") FILTER (WHERE "AGE_REF" ::DECIMAL BETWEEN 19 AND 25) AS avg_family_pretax_income_ref_19_25,
		COUNT("AGE2") FILTER (WHERE "AGE2" <> '' AND "AGE2" ::DECIMAL BETWEEN 19 AND 25) AS spouse_19_25,
		COUNT("NEWID") FILTER (WHERE "AGE_REF" ::DECIMAL BETWEEN 26 AND 35) AS ref_26_35,
    SUM("FINCBTAX" ::DECIMAL) FILTER (WHERE "AGE_REF" ::DECIMAL BETWEEN 26 AND 35) / COUNT("FINCBTAX") FILTER (WHERE "AGE_REF" ::DECIMAL BETWEEN 26 AND 35) AS avg_family_pretax_income_ref_26_35,
		COUNT("AGE2") FILTER (WHERE "AGE2" <> '' AND "AGE2" ::DECIMAL BETWEEN 26 AND 35) AS spouse_26_35,
		COUNT("NEWID") FILTER (WHERE "AGE_REF" ::DECIMAL BETWEEN 36 AND 45) AS ref_36_45,
    SUM("FINCBTAX" ::DECIMAL) FILTER (WHERE "AGE_REF" ::DECIMAL BETWEEN 36 AND 45) / COUNT("FINCBTAX") FILTER (WHERE "AGE_REF" ::DECIMAL BETWEEN 36 AND 45) AS avg_family_pretax_income_ref_36_45,
		COUNT("AGE2") FILTER (WHERE "AGE2" <> '' AND "AGE2" ::DECIMAL BETWEEN 36 AND 45) AS spouse_36_45,
		COUNT("NEWID") FILTER (WHERE "AGE_REF" ::DECIMAL BETWEEN 46 AND 55) AS ref_46_55,
    SUM("FINCBTAX" ::DECIMAL) FILTER (WHERE "AGE_REF" ::DECIMAL BETWEEN 46 AND 55) / COUNT("FINCBTAX") FILTER (WHERE "AGE_REF" ::DECIMAL BETWEEN 46 AND 55) AS avg_family_pretax_income_ref_46_55,
		COUNT("AGE2") FILTER (WHERE "AGE2" <> '' AND "AGE2" ::DECIMAL BETWEEN 46 AND 55) AS spouse_46_55,
		COUNT("NEWID") FILTER (WHERE "AGE_REF" ::DECIMAL BETWEEN 56 AND 65) AS ref_56_65,
    SUM("FINCBTAX" ::DECIMAL) FILTER (WHERE "AGE_REF" ::DECIMAL BETWEEN 56 AND 65) / COUNT("FINCBTAX") FILTER (WHERE "AGE_REF" ::DECIMAL BETWEEN 56 AND 65) AS avg_family_pretax_income_ref_56_65,
		COUNT("AGE2") FILTER (WHERE "AGE2" <> '' AND "AGE2" ::DECIMAL BETWEEN 56 AND 65) AS spouse_56_65,
		COUNT("NEWID") FILTER (WHERE "AGE_REF" ::DECIMAL BETWEEN 66 AND 75) AS ref_66_75,
    SUM("FINCBTAX" ::DECIMAL) FILTER (WHERE "AGE_REF" ::DECIMAL BETWEEN 66 AND 75) / COUNT("FINCBTAX") FILTER (WHERE "AGE_REF" ::DECIMAL BETWEEN 66 AND 75) AS avg_family_pretax_income_ref_66_75,
		COUNT("AGE2") FILTER (WHERE "AGE2" <> '' AND "AGE2" ::DECIMAL BETWEEN 66 AND 75) AS spouse_66_75,
		COUNT("NEWID") FILTER (WHERE "AGE_REF" ::DECIMAL BETWEEN 76 AND 85) AS ref_76_85,
    SUM("FINCBTAX" ::DECIMAL) FILTER (WHERE "AGE_REF" ::DECIMAL BETWEEN 76 AND 85) / COUNT("FINCBTAX") FILTER (WHERE "AGE_REF" ::DECIMAL BETWEEN 76 AND 85) AS avg_family_pretax_income_ref_76_85,
		COUNT("AGE2") FILTER (WHERE "AGE2" <> '' AND "AGE2" ::DECIMAL BETWEEN 76 AND 85) AS spouse_76_85,
		COUNT("NEWID") FILTER (WHERE "AGE_REF" ::DECIMAL > 85) AS ref_over_85,
    SUM("FINCBTAX" ::DECIMAL) FILTER (WHERE "AGE_REF" ::DECIMAL > 85) / COUNT("FINCBTAX") FILTER (WHERE "AGE_REF" ::DECIMAL > 85) AS avg_family_pretax_income_ref_over_85,
		COUNT("AGE2") FILTER (WHERE "AGE2" <> '' AND "AGE2" ::DECIMAL > 85) AS spouse_over_85,
		ROUND(AVG("AGE_REF" ::DECIMAL), 2) AS ref_avg_age,
		ROUND(SUM("AGE2" ::DECIMAL) FILTER (WHERE "AGE2" <> '') / COUNT("AGE2"), 2) AS spouse_avg_age
FROM data_import.cex_pumd_fmli
GROUP BY "QINTRVYR", "QINTRVMO", "REGION"
ORDER BY year, date, region

