SELECT
	"QINTRVYR" ::INTEGER AS year,
	CASE
		WHEN "QINTRVMO" IN ('01', '02', '03') THEN 1
		WHEN "QINTRVMO" IN ('04', '05', '06') THEN 2
		WHEN "QINTRVMO" IN ('07', '08', '09') THEN 3
		WHEN "QINTRVMO" IN ('10', '11', '12') THEN 4
	END AS quarter,
	"QINTRVMO" ::INTEGER AS month,
	TO_DATE (CONCAT ("QINTRVYR", "QINTRVMO"), 'YYYYMM') AS date,
	CASE
		WHEN "REGION" IS NOT NULL AND "REGION" != '' THEN "REGION" ::INTEGER
		WHEN "REGION" IS NULL OR "REGION" = '' THEN 0
	END AS region,
	CASE
		WHEN "REGION" = '1' THEN 'Northeast'
		WHEN "REGION" = '2' THEN 'Midwest'
		WHEN "REGION" = '3' THEN 'South'
		WHEN "REGION" = '4' THEN 'West'
		WHEN "REGION" IS NULL OR "REGION" = '' THEN 'none'
	END AS region_name,
	COUNT("NEWID") AS "total_sample",
	COUNT("AGE2") AS "total_spouse",
	COUNT("NEWID") FILTER (WHERE "AGE_REF" ::DECIMAL <= 18) AS "sample_18_under",
	COUNT("AGE2") FILTER (WHERE "AGE2" <> '' AND "AGE2" ::DECIMAL <= 18) AS "spouse_18_under",
	COUNT("NEWID") FILTER (WHERE "AGE_REF" ::DECIMAL BETWEEN 19 AND 25) AS "sample_19_25",
	COUNT("AGE2") FILTER (WHERE "AGE2" <> '' AND "AGE2" ::DECIMAL BETWEEN 19 AND 25) AS "spouse_19_25",
	COUNT("NEWID") FILTER (WHERE "AGE_REF" ::DECIMAL BETWEEN 26 AND 35) AS "sample_26_35",
	COUNT("AGE2") FILTER (WHERE "AGE2" <> '' AND "AGE2" ::DECIMAL BETWEEN 26 AND 35) AS "spouse_26_35",
	COUNT("NEWID") FILTER (WHERE "AGE_REF" ::DECIMAL BETWEEN 36 AND 45) AS "sample_36_45",
	COUNT("AGE2") FILTER (WHERE "AGE2" <> '' AND "AGE2" ::DECIMAL BETWEEN 36 AND 45) AS "spouse_36_45",
	COUNT("NEWID") FILTER (WHERE "AGE_REF" ::DECIMAL BETWEEN 46 AND 55) AS "sample_46_55",
	COUNT("AGE2") FILTER (WHERE "AGE2" <> '' AND "AGE2" ::DECIMAL BETWEEN 46 AND 55) AS "spouse_46_55",
	COUNT("NEWID") FILTER (WHERE "AGE_REF" ::DECIMAL BETWEEN 56 AND 65) AS "sample_56_65",
	COUNT("AGE2") FILTER (WHERE "AGE2" <> '' AND "AGE2" ::DECIMAL BETWEEN 56 AND 65) AS "spouse_56_65",
	COUNT("NEWID") FILTER (WHERE "AGE_REF" ::DECIMAL BETWEEN 66 AND 75) AS "sample_66_75",
	COUNT("AGE2") FILTER (WHERE "AGE2" <> '' AND "AGE2" ::DECIMAL BETWEEN 66 AND 75) AS "spouse_66_75",
	COUNT("NEWID") FILTER (WHERE "AGE_REF" ::DECIMAL BETWEEN 76 AND 85) AS "sample_76_85",
	COUNT("AGE2") FILTER (WHERE "AGE2" <> '' AND "AGE2" ::DECIMAL BETWEEN 76 AND 85) AS "spouse_76_85",
	COUNT("NEWID") FILTER (WHERE "AGE_REF" ::DECIMAL > 85) AS "sample_over_85",
	COUNT("AGE2") FILTER (WHERE "AGE2" <> '' AND "AGE2" ::DECIMAL > 85) AS "spouse_over_85",
	ROUND(AVG("AGE_REF" ::DECIMAL), 2) AS "sample_avg_age",
	ROUND(SUM("AGE2" ::DECIMAL) FILTER (WHERE "AGE2" <> '') / COUNT("AGE2"), 2) AS "spouse_avg_age"
FROM data_import.cex_pumd_fmli
GROUP BY "QINTRVYR", "QINTRVMO", "REGION"
ORDER BY year, month, region