import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Dainamic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='flex items-center justify-center h-screen text-7xl'>
        <h1 className='m-auto'>
          Welcome to D<span className='text-yellow-300'>AI</span>NAMIC
        </h1>
      </main>
    </div>
  )
}
